#!/usr/bin/env python3
import argparse
import requests

my_parser = argparse.ArgumentParser(description='runs admin elevated commands')
my_parser.add_argument('--passesupd', action='store_true', required=True,
                        help='select the passesupd command, which updates the passes \
                        collection using a csv file with \'--source\' file path')
my_parser.add_argument('--source', metavar='cvs_file_path', type=str, required=True,
                        help='input the file path to the csv file')
args = my_parser.parse_args()

if(args.passesupd):
    try:
        r = requests.post('http://127.0.0.1:9103/interoperability/api/admin/passesupd?filepath=' + args.source)
        if(r.status_code == 200):
            print('200: Success')
        elif(r.status_code == 400):
            print('400: Bad request')
        elif(r.status_code == 500):
            print('500: Internal server error')
        print(r.json())
    except Exception as e:
        print(e)
else:
    print('Error: No command selected')